In [2]:
list=[1,'abs',1.5]

In [3]:
list

[1, 'abs', 1.5]

In [4]:
print(list)

[1, 'abs', 1.5]


In [6]:
print('list')

list


In [7]:
import array as arr

In [8]:
import numpy as np

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr=[[1,2,4],[1,2,3]]

In [25]:
arr

[[1, 2, 4], [1, 2, 3]]

In [28]:
np.shape([[1,2,4],[1,2,3]])

(2, 3)

In [29]:
ab=np.arange(0,11)

In [30]:
ab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
ab[0:1]

array([0])

In [61]:
arr2=np.arange(50)

In [62]:
arr2.argmax()

49

In [64]:
arr2[20]=55
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 55, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
dic={'a':1,'b':2,'c':3}

In [46]:
dic

{'a': 1, 'b': 2, 'c': 3}

In [47]:
a=np.array(dic)

In [48]:
a

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [54]:
dic.keys()

dict_keys(['a', 'b', 'c'])

In [55]:
len(dic)

3

In [56]:
abc='a b c'

In [57]:
abc

'a b c'

In [58]:
abc.split()

['a', 'b', 'c']

In [79]:
import array as arr 
a=arr.array('f', [1.1, 2.2, 3.8, 3.1, 3.7, 1.2, 4.6])

In [71]:
a

array('d', [1.1, 2.2, 3.8, 3.1, 3.7, 1.2, 4.6])

In [74]:
print(a.pop(3))

3.1


In [76]:
a.remove(1.1)

In [77]:
a

array('d', [2.2, 3.8, 3.7, 1.2])

In [90]:
class Employee:
    def __init__(self, name):
        self.name = name
        E1=Employee("abc")
        print(E1.name)

In [91]:
E1.Employee

NameError: name 'E1' is not defined